name: test frontend

on: push

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '13.12.0'

      - run: yarn policies set-version 1.22.4
      - run: yarn install
      - run: yarn test --watchAll=false
