name: mypy

on: push

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.6

      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install --dev --ignore-pipfile
        env:
          CI: 1

      - name: Check types with mypy
        run: |
          pipenv run mypy --ignore-missing-imports --follow-imports=silent server tests
