name: Python test

on: push

jobs:
  build:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:10.11
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: weave_test
        ports:
        - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.6

      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install --dev --ignore-pipfile
        env:
          CI: 1

      - name: Test with pytest
        run: |
          pipenv run test
        env:
          TEST_DATABASE_URL: postgresql://postgres@localhost:${{ job.services.postgres.ports[5432] }}/weave_test
          REACT_APP_SERVER_URL: http://localhost:5000
          SECRET_KEY: test
          FLASK_DEBUG: '1'
